### ISSUE TITLE
Not showing correct Path when working with HasMany-Relationship

### ISSUE THREAD

**Issue by saltbieb** [chris-ware/nova-breadcrumbs#10]
Hey,

thank you for this great package, I really appreciate your work and would like to note a problem I have with it. When working with a HasMany relationship of a resource the breadcrumb path will not work anymore.

For example, when I've got a resource called "Customer" and a single customer should be able to save multiple addresses.

When editing the customer I get the following path: Home / Customer / {CustomerID} / Edit
When I'm creating a new address for this user I get the following path: Home / Address / New instead of Home / Customer / {CustomerID} / Adress / New

Is there any way to fix it?

Thank you for your help.

**Comment by saltbieb** [comment]
Hey Chris,

thank you for your fast response and clarifying the problem. I'm looking forward to your update making use of the VueX mechanic.

**Comment by chris-ware** [comment]
Closing as implementation of this is part of #3
