### ISSUE TITLE
Show resource group as a non-clickable link on the breadcrumb

### ISSUE THREAD

**Issue by abishekrsrikaanth** [chris-ware/nova-breadcrumbs#103]
**Describe the bug**
When a resource has the `$group` set on it, show it as a non-clickable link on the breadcrumb.
**To Reproduce**
1. Open a resource file (example: Blog)
2. set `public static $group = 'CMS';`

**Expected behavior**
The breadcrumb currently shows

```
Home > Blog > Blog Title
```
It would be great if it showed

```
Home > CMS > Blog > Blog Title
```

**Comment by chris-ware** [comment]
@abishekrsrikaanth I wouldn't class this as a bug, more of a feature request, as the groups aren't really breadcrumbs. That being said, I like this idea, I can just see an issue with implementing this in the new version. The new version works with nested relationships to 1 level via query strings. What do you think the nested breadcrumb should do? Examples:

Only load the main resource group:
Home > **Admin** > Users > Chris Ware > Teams > Test Team

Load both resource groups:
Home > **Admin** > Users > Chris Ware > **Admin** > Teams > Test Team

**Comment by abishekrsrikaanth** [comment]
I think the `group` on the breadcrumb should only apply to the Parent and not the children. Let me know what you think

**Comment by chris-ware** [comment]
@abishekrsrikaanth I don't really want to add a config file for the package. That just clogs stuff up. I think for now, due to the way it would work, I'll investigate adding the Parent group only is the way I will do it. I will also do the same thing I have done with the other overrides, where you can adjust it by adjusting the underlying function.

**Comment by abishekrsrikaanth** [comment]
Will this be made available in the current version or will it only be in new major release?

**Comment by chris-ware** [comment]
It'll be in the next major version as that is currently in testing at the moment, with only one issue to resolve at the moment, as its easier to add.

**Comment by chris-ware** [comment]
I can't really see the benefit in adding this as it's just a label that isn't really a breadcrumb as it doesn't have a relevant link to navigate to. I'd accept a PR to merge this behaviour in, as long as it was opt-in rather than opt-out, but at this time, I'm not going to be implementing this.
