### ISSUE TITLE
Problem with translation on index and create

### ISSUE THREAD

**Issue by daguilarm** [chris-ware/nova-breadcrumbs#11]
This is what I have on index:

<img width="444" alt="captura de pantalla 2019-01-24 a las 17 54 54" src="https://user-images.githubusercontent.com/2663941/51694501-3b181180-2001-11e9-9d3b-dcd99e4ea26e.png">

The second item is in English and the translation is not working. The package is using the resource name in english, instead of the label. This problem is also in the create page.

But in the others views: edit and detail, it is working nice (everything in spanish):

<img width="332" alt="captura de pantalla 2019-01-24 a las 17 55 06" src="https://user-images.githubusercontent.com/2663941/51694566-68fd5600-2001-11e9-8ed0-5d6a55bd1651.png">

Great package!

**Comment by chris-ware** [comment]
I believe I have now resolved this issue in 0.6.0. The Index view was pulling the model name from the url string rather than pulling it from the model itself. It should now pull it in line with what you have set up.
