### ISSUE TITLE
Hide dashboard name when only one main dashboard

### ISSUE THREAD

**Issue by DanielLavoie90** [chris-ware/nova-breadcrumbs#110]
Since nova doesn't permit renaming the default dashboard 'main' to something else, I've modified the controller to only show the name of the dashboard if their is multiple dashboards in the project.

NovaBreadcrumbsController.php line 65

```php
if (count(Nova::availableDashboards($request)) >= 1) {
    $this->appendToCrumbs(__(Str::title($request->get('name'))), $pathParts->slice(0, 3)->implode('/'));
}
```

**Comment by chris-ware** [comment]
@DanielLavoie90 Thanks for this, I've implemented this into the next release.
