### ISSUE TITLE
Breadcrums Path not complete

### ISSUE THREAD

**Issue by behrang1981** [chris-ware/nova-breadcrumbs#118]
**Describe the bug**
In my detail view i see a path that seems incomplete to me.

**To Reproduce**
1. Go to the detail page of a resource
https://www.dropbox.com/s/ne3dgkvouj3qjew/Bildschirmfoto%202020-12-04%20um%2013.35.58.png?dl=0

**Expected behavior**
Home (linked) / Resource (linked)  / current item title
what i see is 
Home  (linked) / Resource (unlinked)

**Screenshots**
https://www.dropbox.com/s/ne3dgkvouj3qjew/Bildschirmfoto%202020-12-04%20um%2013.35.58.png?dl=0

**Desktop (please complete the following information):**
 - OS: OSX latest
 - Browser Chrome latest
 - Module Version 2.10

**Additional context**
Is this a bug, a missing feature or my fault?

**Comment by chris-ware** [comment]
@behrang1981 I'm not aware of any issues. Is it just one specific resource or all of them? What version of Nova are you running? What version of Laravel?

**Comment by behrang1981** [comment]
hi,
i have that on all resources:
laravel: 7.30
nova: 3.16.2
and extension: 2.1.1

**Comment by Peterragheb** [comment]
I'm facing the same issue on
laravel: 7.26.0
nova: 3.8.4

**Comment by jvittetoe** [comment]
Same issue here too.

L: 7.30.0
N: 3.16.3
X: 2.1.1

**Comment by chris-ware** [comment]
I've tried to replicate these issues, but as of right now, I haven't been able to. I'm running a site using Laravel Nova 3.16.3, Laravel 7.26 and the latest version of the extension and all seems to work fine. Until I can replicate it, or someone provides a PR to fix this, there isn't much I can do right now.

**Comment by chris-ware** [comment]
Okay, I may have found a possible cause. I've patched and released v2.1.2, hopefully it solves it. If it doesn't, then my above comments still stand.

**Comment by jvittetoe** [comment]
<3 Works perfectly now. I was just about to mention that line in the controller. ty!
