### ISSUE TITLE
Wrong dependency description

### ISSUE THREAD

**Issue by alberto-bottarini** [chris-ware/nova-breadcrumbs#119]
You are using `Str::of` method that is available only starting from Laravel 7.

I installed this package in Laravel 5.8, composer does not complain but code breaks

**Comment by alberto-bottarini** [comment]
I solved adding

```
Str::macro('of', function($string) {
    return new App\Support\Stringable($string);
});
```

in AppServiceProvider

and copying https://raw.githubusercontent.com/laravel/framework/7.x/src/Illuminate/Support/Stringable.php in my codebase

**Comment by chris-ware** [comment]
Ah, this is because I'm limiting it to > Nova 2.7, which supports Laravel 5.8+. I can see why this would cause an issue. This version constraint is solely due to the way that we target Nova Views to implement breadcrumbs.

I think I'll switch to limiting it to Nova 3, which requires Laravel 7+
