### ISSUE TITLE
Multi level breadcrumbs?

### ISSUE THREAD

**Issue by navidnadali** [chris-ware/nova-breadcrumbs#120]
Hi @chris-ware , Great package and thank you very much! 

Is there any way to achieve a multi level breadcrumb? I.e I have a user that goes to Resource X, through there, there is a hasMany relationship so the user clicks on Create to create resource Y.

Nova already has resource X details as it prefills the relevant dropdown with resource X's details. 

Is there any way on the create/view page of resource Y, to have resource X displayed as level 2 (level 3 would then be resource Y?)

Could you point me to anywhere I can start looking to achieve this? Do you foresee any limitations that I will face with the current implementation if I was to extend it to achieve this? 

Thank you very much in advance for your time!

**Comment by chris-ware** [comment]
Hi @navidnadali. We do have very basic support for this via the passed URL arguments. That is the only way that data is passed between pages for relationships. https://github.com/chris-ware/nova-breadcrumbs/blob/eeb77b36c6395ae3ffc09005d86d9b91b5e40f78/src/Http/Controllers/NovaBreadcrumbsController.php#L39 to Line 57.

I have plans for V3, but not the time to work on it right now, that will enable custom implementations of breadcrumbs per resource, so you could implement this in your own project code.

**Comment by navidnadali** [comment]
That's perfect, Thanks @chris-ware just what I needed.

All the best
