### ISSUE TITLE
Class ChrisWare\NovaBreadcrumbs\NovaBreadcrumbs doesn't implement abstract method Laravel\Nova\Tool::menu

### ISSUE THREAD

**Issue by VGirol** [chris-ware/nova-breadcrumbs#133]
I've got this error :
Class ChrisWare\NovaBreadcrumbs\NovaBreadcrumbs contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laravel\Nova\Tool::menu)

**To Reproduce**
1. Install last version (2.3.1)
2. Follow the installation guide
3. See error

**Comment by chris-ware** [comment]
You're trying to use it with nova 4 which isn't supported.

**Comment by VGirol** [comment]
Ah, ok.
I thank you for your quick answer.

If Nova 4 isn't supported, maybe you should change the dependencies in the composer.json :
replace "laravel/nova": ">=3" by "laravel/nova": "^3"

**Comment by chris-ware** [comment]
@VGirol That won't work, as if I were to release a new version with that constraint, composer would just install the version that it believes does support Nova 4. I'd have to delete every tagged version prior to the latest one.

**Comment by VGirol** [comment]
I did not think about that ... ;-)
So, let's leave it as it is.
