### ISSUE TITLE
Nova 4 compatibility?

### ISSUE THREAD

**Issue by saschaende** [chris-ware/nova-breadcrumbs#134]
Class ChrisWare\NovaBreadcrumbs\NovaBreadcrumbs contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laravel\Nova\Tool::menu)

**Comment by saschaende** [comment]
Okay i missed that Nova 4 has this feature built in:

https://nova.laravel.com/docs/4.0/installation.html#enabling-breadcrumbs

**Comment by chris-ware** [comment]
This package doesn't support Nova 4. I can't do anything about the version constraints that allow it.
