### ISSUE TITLE
Loss of filters

### ISSUE THREAD

**Issue by MartinRdw** [chris-ware/nova-breadcrumbs#15]
When I install this package I lose all my custom filters on index pages. Have you seen this behavior?

Without `\ChrisWare\NovaBreadcrumbs\NovaBreadcrumbs::make(),` :

![Capture d’écran 2019-03-20 à 00 22 58](https://user-images.githubusercontent.com/14834643/54648504-ca442180-4aa6-11e9-8130-260ce9a0d28e.png)

With `\ChrisWare\NovaBreadcrumbs\NovaBreadcrumbs::make(),` :

![Capture d’écran 2019-03-20 à 00 25 48](https://user-images.githubusercontent.com/14834643/54648503-ca442180-4aa6-11e9-829d-97a060e41a49.png)

**Comment by chris-ware** [comment]
What version of Nova is this?

**Comment by MartinRdw** [comment]
I have this strange behaviour with Nova v1.2.1 and v2.0.0

**Comment by chris-ware** [comment]
I've just upgraded the package to work with Nova 2.0. Could you update and see if the problem persists? If it does, can you try putting Nova into dev mode as per https://nova.laravel.com/docs/2.0/customization/frontend.html#vue-devtools and see if there is a console error outputted. You may also want to put this package in Dev mode, instructions of which you can find under the contributing notes on the Readme.
