### ISSUE TITLE
Broke pagination

### ISSUE THREAD

**Issue by katieben** [chris-ware/nova-breadcrumbs#16]
This broke my pagination at the bottom - it gave me only a disabled icon when hovering over the navigation arrows.

**Comment by chris-ware** [comment]
What version of Nova are you using?

**Comment by katieben** [comment]
2.0.0

**Comment by katieben** [comment]
The breadcrumbs themselves seem to work perfectly! Nice, needed addition to Nova for me if it just didn't touch the pagination at the bottom.

**Comment by chris-ware** [comment]
I've just upgraded the package to now work with Nova 2.0, which introduced changes to the pagination. This should have resolved it, so please do let me know.

**Comment by katieben** [comment]
Yes, that works, yay! Thanks! :)

**Comment by calvinps** [comment]
With this package (1.0) installed on Nova 2.0.5 I can get pagination to work once, but if I try to click "Next" a second time it is disabled. Uninstalling this package fixed that issue. @chris-ware do you experience the same thing?
