### ISSUE TITLE
Don't working in 2 projects; Work in clean new laravel project;

### ISSUE THREAD

**Issue by sidorenkoda** [chris-ware/nova-breadcrumbs#19]
http://prntscr.com/nlydyq
It's my composer.json

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "alfonsobries/nova-froala-editor": "^1.0",
        "alvinhu/nova-child-select": "^1.0",
        "arrilot/laravel-widgets": "^3.12",
        "barryvdh/laravel-ide-helper": "^2.5",
        "benjaminhirsch/nova-slug-field": "^1.2",
        "bissolli/nova-phone-field": "^0.0.1",
        "chris-ware/nova-breadcrumbs": "^1.0",
        "cloudstudio/resource-generator": "^1.1",
        "coderello/laravel-nova-lang": "^1.0",
        "custom/select": "*",
        "cviebrock/eloquent-sluggable": "^4.6",
        "dinandmentink/nova-markdown": "^0.1.0",
        "ebess/advanced-nova-media-library": "^2.2",
        "enmaboya/nova-russian-datepicker": "*",
        "fideloper/proxy": "^4.0",
        "halimtuhu/array-images": "dev-master",
        "infinety-es/nova-filemanager": "^2.0",
        "infinety-es/nova-menu-builder": "^1.0",
        "jenssegers/agent": "^2.6",
        "johnathan/nova-trumbowyg": "^1.0",
        "laravel/framework": "5.8.*",
        "laravel/nova": "*",
        "laravel/socialite": "^4.1",
        "laravel/tinker": "^1.0",
        "laravelium/sitemap": "3.1.*",
        "mdixon18/fontawesome": "^0.1.0",
        "media24si/nova-youtube-field": "^1.0",
        "ogecut/JsonViewer": "*",
        "ogecut/ajax-select": "*",
        "qcod/laravel-imageup": "^1.0",
        "sbine/route-viewer": "^0.0.5",
        "sidorenkoda/nova-custom": "*",
        "silvanite/novatoolpermissions": "^1.0",
        "socialiteproviders/vkontakte": "^4.0",
        "spatie/laravel-medialibrary": "^7.5",
        "spatie/nova-backup-tool": "^1.1",
        "timothyasp/nova-color-field": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "doctrine/dbal": "^2.9",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "jeroen-g/laravel-packager": "^2.1",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "repositories": [
        {
            "type": "path",
            "url": "./nova"
        },
        {
            "type": "path",
            "url": "./nova-components/NovaCustom"
        },
        {
            "type": "path",
            "url": "./nova-components/Select"
        },
        {
            "type": "path",
            "url": "./nova-components/AjaxSelect"
        },
        {
            "type": "path",
            "url": "./nova-components/nova-russian-datepicker"
        },
        {
            "type": "path",
            "url": "./nova-components/JsonViewer"
        }
    ],
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "Ogecut\\FormsStorage\\": "packages/Ogecut/FormsStorage/src",
            "Ogecut\\FavoriteStore\\": "packages/Ogecut/FavoriteStore/src",
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Ogecut\\FormsStorage\\": "packages/Ogecut/FormsStorage/src",
            "Ogecut\\FavoriteStore\\": "packages/Ogecut/FavoriteStore/src",
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by chris-ware** [comment]
This doesn't provide any information as to how it isn't working. The screenshot shows the breadcrumbs being visible.

**Comment by sidorenkoda** [comment]
👍 On screenshot in breadcrumbs only Home...
But must be Home \ Users ...
And table whitch under breadcrumbs  not loaded
If i disable your plugin - table working

**Comment by chris-ware** [comment]
Are there any outputs into console? Or any network errors?

**Comment by sidorenkoda** [comment]
Console -> http://prntscr.com/np7g02

**Comment by sidorenkoda** [comment]
Sorry :) For fix this problem - php artisan nova:publish
