### ISSUE TITLE
Not working when using eminiarts/nova-tabs

### ISSUE THREAD

**Issue by preliot** [chris-ware/nova-breadcrumbs#20]
I'm using https://github.com/eminiarts/nova-tabs on some of my forms. This does not work well with this package.

Expected: Home / <resource_name> / <specifc_resource> / Edit
Currently: Home /  /  / Edit

**Comment by chris-ware** [comment]
I know this isn't a direct issue between the 2 packages as I am aware of several systems using both without issue, using v1.0.0 of my package and a fairly recent version of both nova and nova-tabs. nova-tabs targets the Vue components inside the views that my package overwrites, so there shouldn't be any conflict there either.

Are there any console outputs? The items are populated by an API call, which is a replica of a standard Nova call, so there may also be information in that API call, though that is less likely.

**Comment by preliot** [comment]
Must have been a bug on my side, it works now like a charm. Appologies for raising a non-existing bug.
