### ISSUE TITLE
Ability to disable breadcrumbs entirely on specific resources

### ISSUE THREAD

**Issue by chris-ware** [chris-ware/nova-breadcrumbs#21]

**Comment by chris-ware** [comment]
The next version, which is switching to API driven, will support this. You can simply overwrite the breadcrumbs function on the resource.

**Comment by viviana-bruno** [comment]
Hi! I'm new to Laravel Nova and I don't understand how to hide breadcrumbs from an specific resource and dashboard. Can you help me?
