### ISSUE TITLE
Version constraints and nova installed from zip

### ISSUE THREAD

**Issue by aphofstede** [chris-ware/nova-breadcrumbs#24]
[The installation instructions](https://nova.laravel.com/docs/1.0/installation.html#installing-nova) use `"laravel/nova": "*",` as version when installing from zip. This seems to break updates of this package now that version constraints were put in place:
```
# composer update chris-ware/nova-breadcrumbs 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for chris-ware/nova-breadcrumbs ^1.0.2 -> satisfiable by chris-ware/nova-breadcrumbs[1.0.2].
    - chris-ware/nova-breadcrumbs 1.0.2 requires laravel/nova >=2.0.0 <=2.0.5 -> no matching package found.
```
Is there a way around this without switching to a composer-based Nova install?

**Comment by chris-ware** [comment]
Version constraints are required for compatibility.

I believe instead of doing `"laravel/nova": "*"`, you should be able to declare the version installed so `"laravel/nova": "2.0.5"`.

**Comment by jdanino** [comment]
Running into the same problem.. trying to update to the latest version but cant because of the version constraints in combination with the zipped version of nova :/

changing to "laravel/nova": "2.0.5" doesn't help unfortunately..

**Comment by aphofstede** [comment]
Same for "* as 2.0.5"

**Comment by chris-ware** [comment]
Unfortunately, there is nothing I can do about this. As I've said previously, the version constraints are required, in order to ensure compatibility with Nova views. This issue is more with Composer than with my package, therefore I shall be closing this issue.
