### ISSUE TITLE
BelongTo with readonly fails with this package

### ISSUE THREAD

**Issue by preliot** [chris-ware/nova-breadcrumbs#25]
With breadcrumbs enabled, readonly doesn't work on BelongsTo. Thought it was a Nova bug, laravel/nova-issues/issues/1637, but it was this package. As soon as this package is disabled, readonly works.

```
 Fields\BelongsTo::make('Description, 'product', Product::class)
            ->readonly(static function ($request) {
                return $request->isUpdateOrUpdateAttachedRequest();
            });

**Comment by preliot** [comment]
But why, dear bot? Please don't close, this is stil an issue.

**Comment by chris-ware** [comment]
I've been able to replicate this, but I think it's an issue that stems from the double up of view mixins. This won't be fixable until Nova adds the custom headers to all views.

**Comment by chris-ware** [comment]
@preliot I'm currently unable to test this, however, thanks to an awesome contributor, we've cleaned up the view overwrites, so that they don't double up the API requests. I'm hoping that this will have addressed the behaviour you are seeing.

**Comment by preliot** [comment]
@chris-ware will try your package again, thanks for the update
