### ISSUE TITLE
pagination links are disabled in Nova 2.0.6 after first paginate

### ISSUE THREAD

**Issue by mziraki** [chris-ware/nova-breadcrumbs#26]

**Comment by chris-ware** [comment]
This package shouldn't be installed on 2.0.6. It hasn't been upgraded to support it and shouldn't allow it via version constraints. I haven't been able to upgrade locally to 2.0.6 via composer for some reason.

**Comment by chris-ware** [comment]
Package has been updated for 2.0.6
