### ISSUE TITLE
How to update this component?

### ISSUE THREAD

**Issue by katieben** [chris-ware/nova-breadcrumbs#27]
Hey there - n00b question. :) How can I update this package? I'm trying to just make this tweak, to get the breadcrumbs not to show up on the Dashboard page:

`<nav v-if="crumbs.length > 1"> `

I'm running 'npm run watch' in my root directory & it's not seeing the change. How can I make the change register?

Thanks!

**Comment by chris-ware** [comment]
Any updates you make inside the package will just get overwritten when it gets updated. Unfortunately, I haven't put in mechanics for disabling breadcrumbs in particular views. 

If you did wish to go ahead with it, I'd suggest removing the references to Dashboard inside the tool.js file. That'll stop it from being added to the Dashboard view.
