### ISSUE TITLE
Use VueX to store path via relationships to allow return back up through relationships

### ISSUE THREAD

**Issue by chris-ware** [chris-ware/nova-breadcrumbs#3]
Currently, breadcrumbs are running via an analysis of the path and breaking them apart. What I'd like to achieve is storing the path down if it's a relationship of the resource.

**Comment by garethnic** [comment]
Nova 1.3.0 released yesterday:

Adds support for registering your own Vuex stores inside custom Nova components.

This might make this feature an easier task, I hope.

**Comment by InfinityWebMe** [comment]
Hello @chris-ware,

any news on this enhancement to support HasMany-Relationship ? 

Thanks ;)

**Comment by chris-ware** [comment]
No news currently. Still planning this as there are a lot of potential pitfalls in implementing this. I think it will be implemented so that it only works when going direct to a related item, not opening it via a new tab or window. It will also only be one level deep, as too many breadcrumbs will make it hard to navigate.

**Comment by tumispro** [comment]
Can't wait for this! I think it's horrible Nova doesn't natively offer breadcrumbs, as you get completely lost after only a few nested relations. Or at least a 'back to parent' button.

**Comment by katieben** [comment]
+1!

**Comment by chris-ware** [comment]
I have a new version of breadcrumbs in the wings which will add some support for relationship tracking, without the need for VueX. I'm the new version is reliant on a core change to Nova that I need to see if I can get merged first, to allow for custom header components on all views.

**Comment by PHPGuus** [comment]
Hi Chris, I take it that this core change hasn't happen, as this "issue" is still open...?

**Comment by chris-ware** [comment]
The change has happened, literally in the latest release (2.7), but the version I was working on back in June is now obsolete as it focused on running an API for Breadcrumbs to be populated. That means further queries on databases, which adds time on larger systems. We managed to get rid of the need to re-query databases sometime ago, with some genius from another collaborator, but now this changes how this needs to be addressed. See #60 for reference.

**Comment by chris-ware** [comment]
With the release of version 2 today, I'm going to close this issue for now. I may re-open or create a new issue for evaluation on a possible version 3, to add support of relationships where Nova doesn't utilise the relationship query string parameters.
