### ISSUE TITLE
broke on Nova 2.0.9

### ISSUE THREAD

**Issue by mziraki** [chris-ware/nova-breadcrumbs#31]

**Comment by chris-ware** [comment]
Please check that the version of Nova you are trying to use is actually supported.

There are version constraints on this package, which should prevent the package from being installed on any version that isn't supported.

The package needs to be rebuilt on every time Nova releases a new version that adjusts the base views.

I've rebuilt it for the latest version.

**Comment by sidorenkoda** [comment]
Hello!
Error isset!

composer.json

"chris-ware/nova-breadcrumbs": "1.0.4",

after "composer update"

composer update
    1/1:        http://repo.packagist.org/p/provider-latest$76f0a0285cc00e8132e068bde3382a85a35c8f0d78ebd8ea19297c738e10e7d6.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for chris-ware/nova-breadcrumbs 1.0.4 -> satisfiable by chris-ware/nova-breadcrumbs[1.0.4].
    - chris-ware/nova-breadcrumbs 1.0.4 requires laravel/nova >=2.0.0 <=2.0.8 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by chris-ware** [comment]
@sidorenkoda 
What version of Nova do you have installed? If it's 2.0.9, then you need to up the version of breadcrumbs in your composer json to the version that supports 2.0.9.

**Comment by sidorenkoda** [comment]
Nova version is 2.0.9
I write "chris-ware/nova-breadcrumbs": "1.0.5",
and get message from composer
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for chris-ware/nova-breadcrumbs 1.0.5 -> satisfiable by chris-ware/nova-breadcrumbs[1.0.5].
    - chris-ware/nova-breadcrumbs 1.0.5 requires laravel/nova >=2.0.0 <=2.0.9 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.


What i must write in composer.json?

**Comment by chris-ware** [comment]
Are you installing nova from a composer repo or from download? If so, at the time composer does versioning checks, there is no way for it to know what version of Nova you are running.

**Comment by sidorenkoda** [comment]
From repo. I download last from github and it work.
But i think that you can delete this string from composer.json http://prntscr.com/oc8l5p

**Comment by chris-ware** [comment]
The version constraints can't be removed from the package as they are there for a reason. As stated in previous issues, if you are using a downloaded copy of nova outside of composer, it isn't able to detect versions. There is nothing I can do about this, aside from suggesting you make use of the composer resource that Nova offers via private authentication.

**Comment by htownson** [comment]
I was receiving the same error as you @sidorenkoda 

I re-installed nova via composer instead of the repo and it is all working fine for me now.
