### ISSUE TITLE
why up to 2.0.9

### ISSUE THREAD

**Issue by bsormagec** [chris-ware/nova-breadcrumbs#39]
Why highest version limited to 2.0.9 it has 2.0.11 now ? can you delete it from composer.json @chris-ware

**Comment by chris-ware** [comment]
If you read the next part of the readme, underneath the current supported version, you will see why.

I haven't had chance to rebuild it to support 2.0.11 yet, which I may add was only released about 36 hours ago. I will rebuild the packages for 2.0.11 support when I get chance.

**Comment by chris-ware** [comment]
I've now re-compiled the package to support 2.0.11
