### ISSUE TITLE
dont working on 2.1.0

### ISSUE THREAD

**Issue by bsormagec** [chris-ware/nova-breadcrumbs#42]
dont working on 2.1.0 can you delete higher version from composer

**Comment by flxsource** [comment]
Duplicate of #39

**Comment by flxsource** [comment]
@bsormagec No, it's a duplicate of the same thing. Read the response in #39 as to why it was closed. If you want to try this package in 2.1.0 yourself, fork the repo and remove the constraints.

The constraints are there for a reason.

> As new versions of Nova are released, if changes are made to any of the views that this package has to overwrite, a new version will need to be released. Composer version constraints should prevent installs on versions that aren't supported.
