### ISSUE TITLE
Issue on create & add another

### ISSUE THREAD

**Issue by chris-ware** [chris-ware/nova-breadcrumbs#47]
TypeError: Cannot read property 'status' of undefined
    at p.<anonymous> (nova-breadcrumbs:1)
    at x (nova-breadcrumbs:1)
    at Generator._invoke (nova-breadcrumbs:1)
    at Generator.e.<computed> [as next] (nova-breadcrumbs:1)
    at n (nova-breadcrumbs:1)
    at nova-breadcrumbs:1
    at new Promise (<anonymous>)
    at new t (nova-breadcrumbs:1)
    at p.<anonymous> (nova-breadcrumbs:1)
    at p.<anonymous> (nova-breadcrumbs:1)

**Comment by chris-ware** [comment]
Not an issue with the package

**Comment by ajthenewguy** [comment]
It absolutely is an issue with the package (look at the stack trace). I ran into this exact error and after commenting out `\ChrisWare\NovaBreadcrumbs\NovaBreadcrumbs::make()` from NovaServiceProvider it does not occur.

**Comment by chris-ware** [comment]
It wasn't an issue with the package at all. In this case, I jumped the gun and thought it was. What was actually happening was I was loading Nova Impersonate on the form pages. It looked like the package causing it, due to the way the views are overwritten.

**Comment by ajthenewguy** [comment]
I was not using this "Nova Impersonate" feature or package. Please read my comment again. This was on a freshly updated Nova install with no other 3rd-party Nova packages. I could generate this _exact_ error with your package enabled, disable it and reload the page with no issues. Then, uncommenting out the line in NovaServiceProvider the issue immediately returns (occurs on refresh).

I don't mean to bother you, I just wanted a breadcrumb in Nova.

**Comment by chris-ware** [comment]
Please don't assume that I haven't read your comment. I completely agree that the stacktrace I inserted in the original comment did say that breadcrumbs was the issue. The explanation I gave explained why that stack trace happened, and what caused it to display as an issue with Breadcrumbs. If you'd like me to explain further, please let me know, or feel free to dig into the code and see for yourself how the views are overwritten.

You've hooked onto an issue that has been closed, simply suggesting the same issue where I have yet been unable to replicate. If you can provide me with your version of Nova, version of Laravel and the version of this package you have installed, as well as your own stacktrace, I can investigate further.
