### ISSUE TITLE
Update Buttons are broken

### ISSUE THREAD

**Issue by bernhardh** [chris-ware/nova-breadcrumbs#5]
When activating nova-breadcrumbs in `NovaServiceProvider` like described, the update buttons are getting broken on edit view:

![image](https://user-images.githubusercontent.com/642292/49738876-c5462980-fc90-11e8-8634-c18331c35d49.png)

They not only look broken, but you can't click them any more. No errors are shown in the browser console.

Commenting out 

```
\ChrisWare\NovaBreadcrumbs\NovaBreadcrumbs::make(),
``` 

from `NovaServiceProvider` and everything works fine again.

**Comment by bernhardh** [comment]
Nope. No log entries. Neither in browser console, nor in /storage/logs/laravel.log

And everthing else looks like its working. Only the edit view "save" buttons have this problem.

**Comment by bernhardh** [comment]
I am on  v1.2.0 atm.

**Comment by chris-ware** [comment]
@bernhardh I've tested this and can't seem to replicate it. I've identified the place where progress-button is injected, which is in the base Nova Update view, which I'm only extending by adding breadcrumbs.

Can you try running npm install and then npm run dev in both your vendor/laravel/nova directory and your vendor/chris-ware/nova-breadcrumbs directory? The first puts nova vue into dev mode as well as installs the dependencies for compiling the breadcrumbs from Nova. The second should put the breadcrumbs into a dev mode through vue as well.

Once you've done the above, try reloading the page and seeing if any console errors appear. At a guess, I would say that there will possibly be one relating to the progress-button component not being found or declared, as that's what the HTML markup would suggest.

**Comment by bernhardh** [comment]
Thanks for feedback. I'm not sure, since I am new to mix/webpack, but is it ment to run`npm run dev` directly inside `vendor/laravel/nova`? I get the following error:

```
Error: Cannot find module '/xxx/vendor/laravel/nova/webpack.mix'
```

As far as I understand it, nova is build from `/` not from `vendor/laravel/nova`.

I have `npm install && npm run dev` in `vendor/chris-ware/nova-breadcrumbs` but nothing changed - the buttons are still broken.

**Comment by florinmatthew** [comment]
@bernhardh what version of Nova do you use please?

**Comment by bernhardh** [comment]
Issue is on `1.2.0` and `1.2.1` as well.

**Comment by chris-ware** [comment]
@bernhardh My apologies, I missed a step. You need to copy the webpack.mix.js.dist file to webpack.mix.js. That'll allow you to run webpack in the nova directory and switch it to dev mode.

**Comment by bernhardh** [comment]
Ok, I have copied `webpack.mix.js.dist` to `webpack.mix.js` in `/nova` and run `npm install`. Then I got the error:

```
ERROR in multi codemirror chartist chartist-plugin-tooltips flatpickr form-backend-validation inflector-js markdown-it marked moment numeral pikaday places.js popper.js vue-async-computed vue-clickaway vue-toasted trix vue vue-router portal-vue lodash moment-timezone axios laravel-nova
Module not found: Error: Can't resolve 'pikaday' in '/home/bernhard/httpdocs/mct/new/nova'
```

I commented the `pikaday` line out and run it again. Afterwards I run `npm run dev` without any errors. Then I run `npm install && npm run dev` on `/`.

But the problem is still there, and no additional debug infos.

**Comment by wefixit-tech** [comment]
there's not solution to this issue bug?

**Comment by chris-ware** [comment]
I haven't yet been able to replicate this bug or find a reason as to why it would happen. If anyone else has been able to replicate it and can follow the steps above to seitch nova into dev mode and provide a console output, I should be able to resolve the issue.

**Comment by wefixit-tech** [comment]
strangely yesterday it did not work and today it works correctly, thanks.

**Comment by bernhardh** [comment]
its still an issue and I don't know why. I just tried a clean install of laravel and nova with just the breadcrumb package and it works without the issue. maybe there is a problem with one of the other packages for nova I installed

**Comment by flxsource** [comment]
@bernhardh It sounds like there's a conflict with another package, yes. Could you try two things to help narrow this down please.

1. Remove this package and confirm that this issue is resolved by that. If it isn't then the problem is elsewhere

2. Reinstall this package, and then remove other nova packages one by one until the problem is fixed - and then let us know which package it was that resolved it.

Thanks

**Comment by bernhardh** [comment]
What I have done so far:

I removed all other tools and cards from `NovaServiceProvider`:

```php
protected function cards() {
    return [];
}

public function tools(){
    return [\ChrisWare\NovaBreadcrumbs\NovaBreadcrumbs::make()];
}
```

Reinstalled all packages:

```bash
rm -rf vendor/*
composer install
npm run watch
```

But same error. 

Thank you for your help anyway, but I don't think I will invest more time to investigate it further.
