### ISSUE TITLE
Squishes search field (missing CSS classes)

### ISSUE THREAD

**Issue by ajthenewguy** [chris-ware/nova-breadcrumbs#50]
For some reason this changes the applied CSS classes to the Index view search field:

Without breadcrumbs: "appearance-none **form-control** **form-input** w-search pl-search"
With breadcrumbs: "appearance-none _form-search_ w-search pl-search _shadow_"

The bolded class names do not appear anymore, and the italicized class names are injected.

This squishes the height of the search field (but only on the Index view).

![Screen Shot 2019-10-08 at 11 22 10 AM](https://user-images.githubusercontent.com/1410914/66422085-e44f3e00-e9bd-11e9-9a63-02e7bcb5d4d0.png)

**Comment by chris-ware** [comment]
Can you let me know what version of Nova this is? I have this installed using the latest version of Nova supported with the latest release and it doesn't cause this issue. It also has the same classes when breadcrumbs is active and when they are disabled.

**Comment by ajthenewguy** [comment]
v2.2.0

**Comment by chris-ware** [comment]
Have you ran the following?
```
php artisan nova:publish
```

**Comment by ajthenewguy** [comment]
I will try that and update with the results on Monday.

**Comment by chris-ware** [comment]
Closing due to no response and unable to reproduce.
