### ISSUE TITLE
Empty Resource and Items

### ISSUE THREAD

**Issue by evelynDickinson** [chris-ware/nova-breadcrumbs#57]
<img width="677" alt="Annotation 2019-10-29 135617" src="https://user-images.githubusercontent.com/4190808/67808436-edc74580-fa53-11e9-9e23-46565d22787b.png">

Hey ya,

Thanks for your work on nova-breadcrumbs! I'm running Laravel 6.2 / Nova 2.5 and Resource and Items are displaying empty once I drill in past the Index page. Any thoughts?

Thanks.

Evie

**Comment by chris-ware** [comment]
The package has a reliance on information generated from API calls, so it should all be there. Are you getting any console errors at all? Being completely empty suggest it has pulled something back as I'm fairly certain I coded it to have a ... by default until its filled

**Comment by evelynDickinson** [comment]
No console errors. Here's the generated code... 

![image](https://user-images.githubusercontent.com/4190808/68061059-3aaf5400-fcc0-11e9-8932-8509e5d00642.png)

**Comment by evelynDickinson** [comment]
Just expanding that a bit...

![image](https://user-images.githubusercontent.com/4190808/68061125-9da0eb00-fcc0-11e9-9467-1afd8eb6f448.png)

**Comment by chris-ware** [comment]
Given that the breadcrumbs don't have any '...' entries, it would suggest that some of the data has tried to be passed into them. This makes it a bit of a pain to debug. One of a few things could be happening here. Firstly, have you updated Nova at all and if so, did you run `php artisan nova:publish` to re-publish all the JS assets? Secondly, are you running any other nova packages, custom or other? Thirdly, does your base resource class have the required Trait in it?
