### ISSUE TITLE
Implement using Custom Header views

### ISSUE THREAD

**Issue by chris-ware** [chris-ware/nova-breadcrumbs#60]
Custom Header views are now available in Nova 2.7.0 in all Views, apparently, according to the release notes. This will remove the need to total overwrite of routes and views and instead, solely use passed data. 

Suggested to shift to new major version on release.

**Comment by vankov1** [comment]
Any luck finding more information about this in the documentation? o.O

**Comment by chris-ware** [comment]
This wouldn't be documented, but it doesn't need to be.

I've made a start on this, however, the way the breadcrumbs interact with Nova currently is by overwriting views and accessing the subview data in order to populate the Breadcrumbs. There is limited data that is passed as props into the custom headers (of which Dashboard doesn't have one, but hasn't worked correctly anyway since multiple dashboards were introduced). This won't be a quick and easy solution, so it may be that this package continues to operate as is until such a time as this becomes a better solution.
