### ISSUE TITLE
Nova 2.9 has been released

### ISSUE THREAD

**Issue by Cannonb4ll** [chris-ware/nova-breadcrumbs#65]
I was also wondering why the versioning is so strict in this package?  Usually when you're in a 2.* version you should be safe to support that all the way through.

**Comment by chris-ware** [comment]
2.9 was released last night, and I haven't had chance to recompile the assets yet.

The README for this package explains why the versioning is strict. Essentially we overwrite the base views for nova. To ensure compatibility, the view we overwrite always has to be compatible with the version of Nova in use. 

I will be recompiling this later today.

**Comment by Cannonb4ll** [comment]
Okay, my bad, didn't read through. Meanwhile there's been several releases on 2.9 I noticed. I will await, thank you!
