### ISSUE TITLE
Problems to install with Nova 2.9.2

### ISSUE THREAD

**Issue by newtongamajr** [chris-ware/nova-breadcrumbs#68]
Hi,
I'm updating my Laravel Nova to 2.9.2 and then tried to execute an update which resulted on errors about the version compatibility between nova-breadcrumbs and nova.
So, to have success on installing Nova 2.9.2, I removed nova-breadcrumbs and then executed a 'composer update' and then Nova 2.9.2 was successfully installed.
My next step was to restore nova-breadcrumbs but I received the same error messages from my previous attempt:

newton@newton-VirtualBox:~/git/laravel/nova/galileo$ composer.phar require chris-ware/nova-breadcrumbs
Using version ^1.2 for chris-ware/nova-breadcrumbs
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - chris-ware/nova-breadcrumbs 1.2.9 requires laravel/nova >=2.0.0 <=2.6.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.8 requires laravel/nova >=2.0.0 <=2.5.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.7 requires laravel/nova >=2.0.0 <=2.4.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.6 requires laravel/nova >=2.0.0 <=2.3.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.5 requires laravel/nova >=2.0.0 <=2.3.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.4 requires laravel/nova >=2.0.0 <=2.2.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.3 requires laravel/nova >=2.0.0 <=2.1.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.2 requires laravel/nova >=2.0.0 <=2.1.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.13 requires laravel/nova >=2.0.0 <=2.9.2 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.12 requires laravel/nova >=2.0.0 <=2.9.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.11 requires laravel/nova >=2.0.0 <=2.8.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.10 requires laravel/nova >=2.0.0 <=2.7.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.1 requires laravel/nova >=2.0.0 <=2.0.11 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.0 requires laravel/nova >=2.0.0 <=2.0.9 -> no matching package found.
    - Installation request for chris-ware/nova-breadcrumbs ^1.2 -> satisfiable by chris-ware/nova-breadcrumbs[1.2.0, 1.2.1, 1.2.10, 1.2.11, 1.2.12, 1.2.13, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
newton@newton-VirtualBox:~/git/laravel/nova/galileo$ composer.phar require chris-ware/nova-breadcrumbs:1.2.12
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for chris-ware/nova-breadcrumbs 1.2.12 -> satisfiable by chris-ware/nova-breadcrumbs[1.2.12].
    - chris-ware/nova-breadcrumbs 1.2.12 requires laravel/nova >=2.0.0 <=2.9.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

I suppose that composer is not checking correctly the version order:

[1.2.0, 1.2.1, 1.2.10, 1.2.11, 1.2.12, 1.2.13, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9]

**Comment by chris-ware** [comment]
How have you installed Nova? Via the private repo or via local install?

**Comment by newtongamajr** [comment]
Local Install, Chris...

**Comment by chris-ware** [comment]
This isn't an issue with this package, but rather using composer with local packages. If you are installing locally, then composer isn't aware of the installed version of Nova, therefore it can't determine which version of this package to install.

Closing this issue as there is nothing further I can assist with at this time.

**Comment by nilsE** [comment]
sorry - i ran into the same problem. how can this be fixed?

thanks,
nils

**Comment by chris-ware** [comment]
By using the private packagist details that Nova supplies you with. That is the only way composer can determine the version of Nova that is installed.

**Comment by nilsE** [comment]
@chris-ware ok, thanks, changed it to composer
