### ISSUE TITLE
Breadcrumbs don't show resource name if the ID is not an integer

### ISSUE THREAD

**Issue by rovansteen** [chris-ware/nova-breadcrumbs#7]
Hello 👋🏼

This package assumes that the ID is an integer by checking for `NaN` [here](https://github.com/chris-ware/nova-breadcrumbs/blob/master/resources/js/components/Breadcrumbs.vue#L27) to decide if it's the link to the resource index or detail. This doesn't work if you use UUID's for example. I think it would be better to do an equality check with the ID from the Nova API or turn it around and check if the link is the resource index and if it's not it's the resource.

#### Pull request

I wanted to create a PR for this but couldn't get the local build to work, maybe because of the custom webpack config. Go the following error:
```
ERROR in /node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!/vendor/laravel/nova/resources/js/views/Dashboard.vue
Module build failed: TypeError: this.setDynamic is not a function
```
Do you have any instructions to set up it up locally?

**Comment by chris-ware** [comment]
The steps for local development should be as follows:

1. copy the webpack.mix.js.dist file to webpack.mix.js inside your nova directory (probably in vendor/laravel)
2. run npm install & npm run dev in both your nova directory and the breadcrumbs directory
3. You then only need to recompile the breadcrumbs assets via npm run dev when building.

I will also take a look at this as I didn't consider the use case where the nova path isn't based around an auto-incrementing ID.

**Comment by chris-ware** [comment]
I have now rewritten the logic that controls the breadcrumb labels, so it now relies solely on what the ID is set rather than doing a NaN check. This allows for UUIDs to be used.
