### ISSUE TITLE
Any special configuration to enable Attach and AttachUpdated

### ISSUE THREAD

**Issue by abishekrsrikaanth** [chris-ware/nova-breadcrumbs#78]
Thanks a lot for this package. It works great. I am still having a bit of trouble to get this to work on the Attach and AttachUpdated screens of the resource. Is there any specific configuration required in addition to using the trait?

When I go to the Attach (HasMany, HasOne relations) and AttachUpdated screens, it only shows me `Home / Attached Resource / Attached Resource Title` instead of `Home / Resource / Attached Resource / Attached Resource Title`. How do I get this to work?

**Comment by chris-ware** [comment]
There shouldn't need to be. It may be that something has changed behind the scenes and I just need to tweak the breadcrumb generation. Can you let me know what package version and Nova version you are using please?

**Comment by chris-ware** [comment]
I've just taken a look at one of my examples for this. The following should be the case:
Attach: Home / Resource Name / Resource Title
UpdateAttached: Home / Resource Name / Resource Title / Attached Resource Title

It won't ever show the attached resource name, as there is no direct/separate link to it, so having it as a breadcrumb to it is pointless as it would go to a URL that does not exist. I could put in an unlinked breadcrumb, but that has 2 issues. 

1. Breadcrumbs uses the RouterLink component, so I'd have to put a conditional in to switch between that and standard markup.
2. Having an breadcrumbs element that isn't clickable or linked might confuse users.

**Comment by abishekrsrikaanth** [comment]
I am on Nova `v2.10.1`. My point is, the `Attach` and the `UpdateAttached` doesn't show the Parent Resource on the breadcrumb to indicate what Resource it is being attached to. Let me know if that clarifies.

**Comment by chris-ware** [comment]
I've tested this, and I'm unable to see any issues here.

In my example, I have users and roles. 
Attach: Home/Users/Chris Ware
EditAttached: Home/Users/Chris Ware/Super Admin

Are you able to provide screenshots and examples?

Have you run `artisan nova:publish` since updating Nova?
