### ISSUE TITLE
Create Resource not work in 1.2.17 with Nova v2.10.1

### ISSUE THREAD

**Issue by Equruler** [chris-ware/nova-breadcrumbs#83]
Using:
nova-breadcrumbs 1.2.17
nova v2.10.1

Create Resource show nothing:
![image](https://user-images.githubusercontent.com/27337895/74336562-7be3f380-4dd9-11ea-9651-5a5638e827b8.png)

but
View Resource
Update Resource
still works.

My composer.json requires:

```
    "require": {
        "php": "^7.2",
        "causelabs/resource-index-link": "^1.0",
        "chris-ware/nova-breadcrumbs": "^1.2",
        "digital-creative/collapsible-resource-manager": "^1.2",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/nova": "~2.0",
        "laravel/tinker": "^2.0",
        "novius/laravel-nova-order-nestedset-field": "^0.3.0@alpha",
        "optimistdigital/nova-translatable": "^1.2",
        "spatie/laravel-translatable": "^4.2",
        "whitecube/nova-flexible-content": "^0.1.15"
    },
```

**Comment by sblomberg** [comment]
Can confirm that we encountered problems with the Create Resource views in our project after upgrading to `chris-ware/nova-breadcumbs v1.2.17` and `laravel/nova v2.10.1`. After running `php artisan nova:publish` the Create Resource view loaded the new resource fields, but we are unable to save new resources due to a 500 error and the breadcrumbs do not populate on that view.

All other resource views are working as expected.

**Comment by Equruler** [comment]
Thanks for your quick reply!

**Comment by I3G-Carlos** [comment]
Also can confirm, there's a compatibility issue when creating resources.

Laravel 6.2
Nova 2.10.1
nova-breadcrumbs: 1.2.17

**Comment by chris-ware** [comment]
I will take a look at this as soon as I can

**Comment by chris-ware** [comment]
1.2.18 should resolve this. Looks like it's an issue with Nova's 2.10 release as a whole, as they've replaced the Create view with a CreateForm inside it, so the data has to be pulled from that instead. Hopefully my testing changes have pull across correctly and this is no longer a problem.

**Comment by Equruler** [comment]
Thanks Chris!

**Comment by newtongamajr** [comment]
@chris-ware , I had upgraded to 1.2.18 and the create view remain not appearing. After removing breadcrumbs, create view was presented.

**Comment by chris-ware** [comment]
Have you run artisan nova:publis?

**Comment by newtongamajr** [comment]
After republishing it worked fine.. thank's @chris-ware !

**Comment by chris-ware** [comment]
Closing as this now seems to be solved with 1.2.18.

**Comment by GaillardQ** [comment]
Hello,
I still have the problem....

Laravel 6.2
Nova 2.11
nova-breadcrumbs: 1.2.19

I launched theses commands :
- php artisan nova:publish (with and without --force)
- php artisan view:clear
- php artisan config:cache
- php artisan serve
- cleaned browser cache
- logout/login

And I still have the same error....

[Vue warn]: Unknown custom element: <create-form> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
[Vue warn]: Error in getter for watcher "function(){return e.$refs.rview.$children[0].loading}": "TypeError: Cannot read property 'loading' of undefined"

**Comment by chris-ware** [comment]
@GaillardQ I'm not quite sure what would cause this, unless you have another package that adjusts the Create View. I've checked, and the code should work. Does it work fine when this package is disabled? Something seems to be preventing the 'create-form' component from being registered in the children namespace at position 0 for the Create View.
