### ISSUE TITLE
TypeError: Cannot read property 'loading' of undefined

### ISSUE THREAD

**Issue by bigperson** [chris-ware/nova-breadcrumbs#88]
![image](https://user-images.githubusercontent.com/4757391/76964017-09fc4e00-6933-11ea-9648-9d301226ca47.png)

**Comment by chris-ware** [comment]
I need a little more than just a screenshot. Can you let me know the following:
- Nova Version
- Breadcrumbs Version

I'm assuming this relates to the Create View as that is the only one with the children lookup, but can you confirm how you got to the page that produced this error?

**Comment by Bessamu** [comment]
Hello!

* Nova version - 2.9.2
* Breadcrumbs version - 1.2.20

Yes, that happens only in Create view.

**Comment by thibodelanghe** [comment]
Hi, this error also occurs in my case https://github.com/chris-ware/nova-breadcrumbs/issues/89

**Comment by chris-ware** [comment]
> Hi, this error also occurs in my case #89

The error presented in #89 and this error are 2 distinctly different errors. Please don't relate them when they aren't related.

**Comment by chris-ware** [comment]
@Bessamu You either need to downgrade your instance of Nova Breadcrumbs to the version that matches your Nova install or update Nova to the latest supported version. The packages have too open version requirements that allow newer versions to be installed on older packages.
