### ISSUE TITLE
Hide breadcrumb until information has been loaded

### ISSUE THREAD

**Issue by izi-dev** [chris-ware/nova-breadcrumbs#98]
thanks for this package, it works perfect.

Just one thing, I would like the breadcrumb to be hidden until all your information is complete.

**Comment by chris-ware** [comment]
This isn't really possible in the current version as each of the views have a different amount of items to load and each of them loads slightly differently.

In Version 2, which I haven't had time to work on, this will be a single API request, so I can await a response from the API. I probably will still load something as it may look weird breadcrumbs suddenly appearing and pushing content down. Alternatively, I may just add classes allowing you to control this yourself.

**Comment by chris-ware** [comment]
Version 2 has now been released, where the entirety of the breadcrumbs only loads when all information is set.
