### ISSUE TITLE
403 when view policy is disabled. 

### ISSUE THREAD

**Issue by nchornii** [chris-ware/nova-breadcrumbs#99]
**Describe the bug**
When disabled view via policy and tried to edit resources getting 403 exception. 

**To Reproduce**
1. Disable the ability to view via policy. 
```
class ArtikelPolicy
{
    public function viewAny(User $user)
    {
        return $user->hasRole(['Key Account Sales', 'Test Admin']) || $user->isAdmin();
    }

    public function view(User $user, Artikel $artikel)
    {
        return false;
    }
}
```
2. Try to edit the resource.

**Expected behavior**
Opens to edit page

**Screenshots**
![image](https://user-images.githubusercontent.com/62063744/84684368-3da24080-af41-11ea-9b2b-fea9dae7046c.png)

**Desktop (please complete the following information):**
- all browsers

**Additional context**
Found in `./vendor/chris-ware/nova-breadcrumbs/resources/js/mixins/FetchResource.vue` this code:
```
 getResource() {
                this.resource = null

                return Minimum(
                    Nova.request().get('/nova-api/' + this.resourceName + '/' + this.resourceId)
                )
                    .then(({data: {panels, resource}}) => {
                        this.resource = resource
                        this.loading = false
                    })
```

`Nova.request().get('/nova-api/' + this.resourceName + '/' + this.resourceId)` couses error.

**Comment by chris-ware** [comment]
Have you tested that the same behaviour happens when Breadcrumbs is disabled? We don't do anything with policies, so I'm hessitant to suggest this is an issue with Breadcrumbs.

**Comment by chris-ware** [comment]
Can you ltet me know the version of Laravel, Nova and Breadcrumbs you are using?

**Comment by nchornii** [comment]
@chris-ware
chris-ware/nova-breadcrumbs: v1.3.6
laravel/framework: 7.13.0
laravel/nova: 3.6.0

**Comment by chris-ware** [comment]
@nchornii Thanks. This does make sense, as the way that I have to retrieve data is via the Mixin. 

I'll see if I can do anything about this, but it may not be possible in this version. It may have to wait until I finally get around to building version 2. I would ask however, why someone can't view an item but can edit it?

**Comment by nchornii** [comment]
@chris-ware I get it - thanks. This is some project restrictions, I can't change it :(

**Comment by chris-ware** [comment]
@nchornii I know the Bot auto-closed this, but with the release of Version 2, I'm hoping this solves your issues you were having as there is no reliance on Policy based API calls anymore.
